services:
  - type: web
    name: exchange_api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-t!71*t*d_#@(fv11skv2wtsqp5w1jxz%ujg+4)p!m76)14sn42

      - key: DEBUG
        value: "False"

      - key: POSTGRES_DB
        value: exchangedb_skkj

      - key: POSTGRES_USER
        value: aziret

      - key: POSTGRES_PASSWORD
        value: ij6xA7LHlhoaPmRYuWaBqKOo452sa9xR

      - key: DB_HOST
        value: dpg-d01j39re5dus73b8fs10-a.oregon-postgres.render.com

      - key: DB_PORT
        value: 5432

      - key: ALLOWED_HOSTS
        value: exchangeback-sxhp.onrender.com